# Hệ phương trình tuyến tính

Biên soạn: Lê Xuân Trường

## Một số vấn đề cơ bản 

Xét hệ phương trình tuyến tính có dạng ma trận như sau

$$
    Ax = b
$$

trong đó $A$ là ma trận cấp $m \times n$ và $b \in \mathbb{R}^n$. Đây là một hệ gồm có $m$ phương trình và $n$ ẩn số.

__Định lý: (Kronecker-Capelli)__

Ký hiệu $\bar{A} = [A \,\, b]$ là ma trân hệ số mở rộng. Ta có các kết quả sau

* Nếu $rank(\bar{A}) >  rank(A)$ thì hệ phương trình vô nghiệm

* Nếu $rank(\bar{A}) =  rank(A) = n$ thì hệ phương trình có duy nhất nghiệm

* Nếu rank$(\bar{A}) =  rank(A) < n$ thì hệ phương trình có có vô số nghiệm phụ thuộc vào $n - \text{rank}(A)$ tham số.

__Phương pháp giải đúng:__

* Phương pháp khử Gauss

* Phương pháp khử Gauss-Jordan

## Phương pháp phân tích LU

### Tại sao?

Trong thực tế ta thường gặp tình huống phải tìm nghiệm của các hệ phương trình

$$
    Ax = b_1, \quad Ax = b_2, \quad Ax = b_3, \quad ....
$$

Các hệ phương trình này có cùng ma trận hệ số đầu vào nhưng véctơ ở vế phải là khác nhau. Trong khi đó, để giải hệ phương trình bằng phương pháp khử Gauss hoặc phương pháp khử Gauss-Jordan ta phải biến đổi ma trận hệ số mở rộng về dạng bậc thang. Dường như việc thực hiện điều này nhiều lần trên các ma trận chỉ khác nhau ở cột cuối cùng là một cách tiếp cận không hiệu quả. Phương pháp LU sẽ khắc phục nhược điểm trên và giúp cho quá trình giải các hệ phương trình có cùng ma trận hệ số hiệu quả hơn.

### Phân tích LU là gì?

Phân tích LU của một ma trận vuông $A$ là việc biểu diễn $A$ dưới dạng __$A = LU$__ trong đó $L$ là một ma trận tam giác dưới (tất cả các phần tử trên đường chéo chính bằng 1) và $U$ là một ma trận tam giác trên.

_Ví dụ 1:_
$$
    \begin{bmatrix} 1 & 2 & 4 \\ 3 & 8 & 14 \\ 2 & 6 & 13 \end{bmatrix} = 
    \begin{bmatrix} 1 & 0 & 0 \\ 3 & 1 & 0 \\ 2 & 1 & 1 \end{bmatrix}.
    \begin{bmatrix} 1 & 2 & 4 \\ 0 & 2 & 2 \\ 0 & 0 & 3 \end{bmatrix}
$$

_Ví dụ 2:_ Tìm phân tích LU của ma trận $A = \begin{bmatrix} 3 & 1 \\ -6 & -4 \end{bmatrix}$.


### Phân tích LU của một ma trận vuông luôn tồn tại?

Câu trả lời là không phải. Ma trận vuông phải thoả các điều kiện nhất định thì mới có phân tích LU. Cụ thể hơn ta có kết quả sau:

__Định lý: (Điều kiện đủ cho phân tích LU)__ 

Nếu mọi định thức con chính (định thức của ma trận gồm các phần tử nằm ở giao của $k$ dòng đầu và $k$ cột đầu) của một ma trận vuông $A$ đều khác 0 thì $A$ có phân tích LU duy nhất.

_Ví dụ 3:_ Chỉ ra rằng ma trận sau có duy nhất một phân tích LU

$$
    A = \begin{bmatrix} 2 & 1 & 1 \\ 4 & -6 & 0 \\ -2 & 7 & 2 \end{bmatrix}
$$ 

### Mô tả phương pháp:

__Tìm phân tích LU bằng phép biến đổi sơ cấp__

Giả sử ma trận $A_{n \times n}$ có thể biến đổi thành ma trận bậc thang dòng $U$ bằng các phép biến đổi sơ cấp loại 3

$$
    A \xrightarrow[i = 1,...,n-1; \,\, j = i+1,...,n]{R_j \longrightarrow R_j - m_{ji}R_i} U.
$$

Ký hiệu $L$ là ma trận tam giác dưới với các phần tử 

$$
    \ell_{ij} = \begin{cases} m_{ij} & i > j, \\ 1 & i = j, \\ 0 & i < j. \end{cases}
$$


Khi đó ta có $A = LU$.

_Ví dụ 4:_ Với ma trận $A$ trong _Ví dụ 3_, ta có

$$
    A \xrightarrow[R_3 \longrightarrow R_3 + R_1]{R_2 \longrightarrow R_2 - 2R_1} \begin{bmatrix} 2 & 1 & 1 \\ 0 & -8 & -2 \\ 0 & 8 & 3 \end{bmatrix} \xrightarrow{R_3 \longrightarrow R_3 + R_2} \begin{bmatrix} 2 & 1 & 1 \\ 0 & -8 & -2 \\ 0 & 0 & 1 \end{bmatrix} \equiv U.
$$


$$
    (m_{21} = 2, \quad m_{31} = -1, \quad m_{32} = -1)
$$


Đặt $L = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -1 & -1 & 1 \end{bmatrix} $. Khi đó ta có $A = LU$.

__Thuật toán Doolittle__

Với mỗi $i \in \{1, 2, ..., n\}$:

* Tính $u_{ij} = a_{ij} - \sum\limits_{k=1}^{i-1}\ell_{ik}u_{kj}$ với $j = i, i+1, ..., n$ $\Longrightarrow$ các dòng của ma trận $U$

* Tính $\ell_{ji} = \frac{1}{u_{ii}}\big[a_{ji} - \sum\limits_{k=1}^{i-1}\ell_{jk}u_{ki}\big]$ với $j = i+1,...,n$ và $\ell_{ii} = 1$ $\Longrightarrow$ các cột của ma trận $L$ 

_Ví dụ 5:_ Ta cũng xét ma trận $A$ trong ví dụ 3 và sử dụng thuật toán Doolittle.

* Với $i=1$ ta có

$$
    u_{11} = a_{11} =  2, \quad u_{12} = a_{12} = 1, \quad u_{13} = a_{13} = 1.
$$

$$
    \ell_{11} = 1, \quad \ell_{21} = \frac{1}{2}.(4) = 2, \quad \ell_{31} = \frac{1}{2}(-2) = -1
$$

* Với $i = 2$

$$
    u_{22} = a_{22} - \ell_{21}u_{12} = -6 - 2.1 = -8, \quad u_{23} = a_{23} - \ell_{21}u_{13} = 0 - 2.1 = -2 
$$

$$
   \ell_{22} = 1, \quad \ell_{32} = \frac{1}{u_{22}}\big[a_{32} - \ell_{31}.u_{12}\big]= \frac{1}{-8}[7 - (-1).1] = -1
$$

* Với $i = 3$

$$
    u_{33} = a_{33} - \ell_{31}u_{13} - \ell_{32}u_{23} = 2 - (-1).1 - (-1)(-2) = 1, \quad \ell_{33} = 1.
$$

Vậy ta thu được $U = \begin{bmatrix} 2 & 1 & 1 \\ 0 & -8 & -2 \\ 0 & 0 & 1 \end{bmatrix}$ và $L = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ -1 & -1 & 1 \end{bmatrix}$.

### Phân tích PLU với Python:

Ta có thể thấy rằng phương pháp phân tích LU được nói ở trên sẽ gặp trở ngại khi có một phần tử nằm trên đường chéo $a_{ii} = 0$. Ta có thể khắc phục điều này bằng cách đổi chỗ dòng $i$ với dòng đầu tiên phía dưới có phần tử nằm ở cột thứ $i$ khác 0. Việc hoán đổi này sẽ được ghi nhận thông qua một ma trận $P$ (gọi là ma trận hoán vị). Ma trận này có đặc điểm là ở mỗi dòng và mỗi cột đều có một số 1 và các số còn lại bằng 0.

Chẳng hạn như nếu 
$$
    A = \begin{bmatrix} 0 & 3 & 1 \\ 1 & -2 & 4 \\ 3 & -1 & 5 \end{bmatrix} \xrightarrow{R_1 \leftrightarrow R_2} 
    \begin{bmatrix} 1 & -2 & 4 \\ 0 & 3 & 1 \\ 3 & -1 & 5 \end{bmatrix} = B
$$

thì ta có thể viết $A = PB$, trong đó $P = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}$. Khi đó tiến hành phân tích LU cho B, ta thu được phân tích PLU của $A$

$$
    A = PLU.
$$


Sử dụng thư viện linalg của gói __scipy__ để phân tích PLU của một ma trận như ví dụ sau

In [15]:
import numpy as np
from scipy.linalg import lu

A = np.array([[3,1,6], [-6, 0, -16], [0, 8, -17]])

P, L, U = lu(A)
print("P:\n ",P)
print("L: \n",L)
print("U: \n",U)

P:
  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L: 
 [[ 1.     0.     0.   ]
 [-0.     1.     0.   ]
 [-0.5    0.125  1.   ]]
U: 
 [[ -6.      0.    -16.   ]
 [  0.      8.    -17.   ]
 [  0.      0.      0.125]]


In [17]:
P@L@U

array([[  3.,   1.,   6.],
       [ -6.,   0., -16.],
       [  0.,   8., -17.]])

### Sử dụng phân tích LU để giải hệ phương trình tuyến tính:

Xét hệ phương trình tuyến tính có dạng ma trận $Ax = b$ với $A$ là ma trận vuông cấp $n$. Giả sử $A$ có phân tích LU

$$
    A = LU.
$$

Khi đó ta tìm nghiệm của hệ phương trình bằng thuật toán sau

* Bước 1: Phân tích LU ma trận hệ số $A$


* Bước 2: Giải hệ phương trình $Ly = b$ (ta đặt $y = Ux$)


$$
    y_1 = b_1/\ell_{11}
$$

    Với i = 2, 3, ..., n ta có

$$
    y_i = \big(b_i - \sum_{j=1}^{i-1}\ell_{ij}y_j\big)/\ell_{ii}
$$


* Bước 3: Giải hệ phương trình $Ux = y$

$$
    x_k = \begin{cases} y_k/u_{kk}, & \text{if} \,\, k = n, \\
    \\
    \big(y_k - \sum_{j=k+1}^nu_{kj}x_j\big)/u_{kk}, & \text{if} \,\, k = n-1, ..., 2, 1. \end{cases}
$$

__Lưu ý:__ Trong trường hợp ta có phân tích PLU của ma trận $A$ thì trước khi thực hiện 3 bước trong thuật toán trên ta tiến hành đổi dòng tương ứng của $b$. Cụ thể hơn, ta thay $b$ bởi $Pb$.

## Phương pháp lặp

Xét hệ phương trình tuyến tính có dạng ma trận như sau, với $A$ là ma trận vuông cấp $n$,

$$
    Ax = b.
$$

Giả sử phương trình trên có nghiệm duy nhất là $x^* = (x_1^*, x_2^*, ..., x_n^*)$.

__Ý tưởng cơ bản:__ của các phương pháp lặp là xây dựng một dãy các véctơ $\{x^{(k)}\}_{k=0}^\infty$ sao cho 

$$
    \lim_{k \to \infty}x^{(k)} = x^*. \quad x^{(k)} = (x_1^{(k)}, x_2^{(k)}, ..., x_n^{(k)})
$$

Điều này có nghĩa là khoảng cách giữa $x^{(k)}$ và nghiệm đúng $x^*$ sẽ tiến về 0 khi $k$ tiến ra vô hạn. Trong thực hành, véctơ $x^{(k)}$ sẽ được tính qua các véctơ 

$$
    x^{(0)}, x^{(1)}, ..., x^{(k-1)}.
$$ 

Quá trình lặp sẽ dừng tại giá trị $k$ nhỏ nhất sao cho $\|x^{(k)} - x^*\| < \varepsilon$, với $\epsilon$ là giá trị xác định trước.

### Khoảng cách giữa hai ma trận

Cho $A=(a_{ij})$ và $B=(b_{ij})$ là hai ma trận vuông cấp $n$. 

* Chuẩn của ma trận $A$ được xác định bởi

$$
    \|A\| = \sqrt{\sum_{i, j = 1}^n |a_{ij}|^2} \quad \text{(chuẩn Euclide của $A$)}
$$

* Khoảng cách giữa hai ma trận $A$ và $B$: $d(A, B) = \|A -B\|$.

### Phương pháp lặp Jacobi và phương pháp lặp Gauss-Seidel
 

* Các phần tử trên đường chéo chính của ma trận hệ số $A$ khác $0$. Với giả thiết này, hệ $Ax = b$ có thể viết lại dưới dạng

$$
    (D-L-U)x = b,
$$

trong đó

$$
    D = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots \\
    0 & 0 & \cdots & a_{nn}
    \end{bmatrix}, \quad \quad D^{-1} = \begin{bmatrix} \frac{1}{a_{11}} & 0 & \cdots & 0 \\ 0 & \frac{1}{a_{22}} & \cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots \\
    0 & 0 & \cdots & \frac{1}{a_{nn}}
    \end{bmatrix} 
$$

và

$$
    L = \begin{bmatrix} 0 & 0 & \cdots & 0 \\ - a_{21} & 0 & \cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots \\
    -a_{n1} & -a_{n1} & \cdots & 0
    \end{bmatrix}, \qquad U = \begin{bmatrix} 0 & -a_{12} & \cdots & -a_{1n} \\ 0 & 0 & \cdots & 0 \\
    \vdots & \vdots & \vdots & -a_{n-1,n} \\
    0 & 0 & \cdots & 0
    \end{bmatrix}
$$

Để giải hệ bằng phương pháp lặp, ta tìm cách viết hệ dưới dạng như sau

$$
    x = Tx + c
$$

Khi đó ta xây dựng dãy $\{x^{(k)}\}$ như sau

* $x^{(0)}$ chọn tuỳ ý


* Tính $x^{(k)} = Tx^{(k-1)} + c$

#### Công thức lặp Jacobi


$$
    (D-L-U)x = b \Longleftrightarrow Dx = (L+U)x + b \Longleftrightarrow x = D^{-1}(L+U)x + D^{-1}b
$$


* Chọn $x^{(0)} \,\, \text{tuỳ ý}$

* Với $k = 1, 2, ...$ ta tính các thành phần của véctơ $x^{(k)}$ bởi công thức

$$
    x^{(k)}_i = \frac{1}{a_{ii}}\left[b_i - \sum_{j = 1, j \neq i}^{n}a_{ij}x^{(k-1)}_j\right]. \quad i = 1, 2,..., n.
$$

_Dạng ma trận_ của công thức lặp Jacobi

$$
    x^{(k)} = D^{-1}(L+U)x^{(k-1)} + D^{-1}b, \quad k = 1, 2, ..., n.
$$

#### Công thức lặp Gauss-Seidel

$$
    (D-L-U)x = b \Longleftrightarrow (D-L)x = Ux + b \Longleftrightarrow x = (D-L)^{-1}Ux + (D-L)^{-1}b
$$

* Chọn $x^{(0)} \,\, \text{tuỳ ý}$

* Với $k = 1, 2, ...$ ta tính các thành phần của véctơ $x^{(k)}$ bởi công thức

$$
    x^{(k)}_i = \frac{1}{a_{ii}}\left[b_i - \sum_{j = 1}^{i-1}a_{ij}x^{(k)}_j -  \sum_{j = i+1}^{n}a_{ij}x^{(k-1)}_j \right]. \quad i = 1, 2,..., n.
$$

_Dạng ma trận_ của công thức lặp Gauss-Seidel:

$$
    x^{(k)} = (D-L)^{-1}Ux^{(k-1)} + (D-L)^{-1}b, \quad k = 1, 2, ..., n.
$$

#### Sự hội tụ

_Định ngĩa:_ Ma trận vuông $A$ được gọi là ma trận được chéo trội nghiêm ngặt nếu, với mỗi dòng, độ lớn của phần tử nằm trên đường chéo chính lớn hơn tổng độ lớn của các phần tử khác của dòng đó.

_Ví dụ:_ 

$$
    A = \begin{bmatrix} 3 & 1 & 0.5 \\ 0.2 & 1 & 0.4 \\ -0.3 & 1 & -2 \end{bmatrix}
$$

là ma trận đường chéo trội nghiêm ngặt. Lý do

$$
    3 > 1 + 0.5, \quad 1 > 0.2 + 0.4, \quad |-2| > 1 + |-0.3|
$$ 


_Định lý:_ 

Nếu ma trận hệ số $A$ là một ma trận đường chéo trội nghiêm ngặt thì dãy lặp $\{x^{(k)}\}_{k=0}^\infty$ trong cả hai phương pháp Jacobi và phương pháp Gauss-Seidel sẽ hội tụ về nghiệm đúng $x^*$. Hơn nữa ta có

$$
    \|x^{(k)} - x^*\| \leq \|T\|^k\|x^{(0)} - x^*\|, \quad  \|x^{(k)} - x^*\| < \frac{\|T\|^k}{1-\|T\|}\|x^{(1)} - x^{(0)}\|.
$$

Ở đây $T = D^{-1}(L+U)$ đối với phương pháp lặp Jacobi và $T = (D-L)^{-1}U$ đối với phương pháp lặp Gauss-Seidel.

Trong thực hành ta thường sử dụng đại lượng

$$
    \|x^{(k)} - x^{(k-1)}\|
$$

để ước lượng sai số.

#### Thuật toán (Jacobi)

* Input: A, b, init, errors, maximum number of iterations N


* Step 1: Set k = 1, x = [] 


* Step 2: While k <= N do Step 3 to Step 5


    * Step 3: for i = 1, 2,..., n
    
        Calculate x_i by using Jacobi's iteration formula


    * Step 4: If d(x, init) < error then 
    
                    Return x
              else
                    k = k + 1        
                    init = x

    * Step 5: Return x

#### Thuật toán Gauss-Seidel

Tương tự như thuật toán Jacobi, chỉ thay công thức ở Step 2 bằng công thức lặp Gauss-Seidel.